
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.stmwr.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.stmwr.item.WizardWorldItem;
import net.mcreator.stmwr.item.WingedAppleItem;
import net.mcreator.stmwr.item.WeakSoulItem;
import net.mcreator.stmwr.item.WandarCoreItem;
import net.mcreator.stmwr.item.WandStickItem;
import net.mcreator.stmwr.item.WandOfTransmutationItem;
import net.mcreator.stmwr.item.WandOfTheTowerItem;
import net.mcreator.stmwr.item.UpgradeStationTutorialSheetItem;
import net.mcreator.stmwr.item.UltriteItem;
import net.mcreator.stmwr.item.UglumItem;
import net.mcreator.stmwr.item.TotemOfTheGoopItem;
import net.mcreator.stmwr.item.TotemOfTheCowItem;
import net.mcreator.stmwr.item.TotemOfSlowFallingItem;
import net.mcreator.stmwr.item.TotemOfLevitationItem;
import net.mcreator.stmwr.item.TortillaItem;
import net.mcreator.stmwr.item.TacoItem;
import net.mcreator.stmwr.item.StrongSoulItem;
import net.mcreator.stmwr.item.StrengthTotemT3Item;
import net.mcreator.stmwr.item.StrengthTotemT2Item;
import net.mcreator.stmwr.item.StrengthTotemT1Item;
import net.mcreator.stmwr.item.StorumItem;
import net.mcreator.stmwr.item.StoraliumItem;
import net.mcreator.stmwr.item.StevumItem;
import net.mcreator.stmwr.item.SteveCowHornItem;
import net.mcreator.stmwr.item.SteelSwordItem;
import net.mcreator.stmwr.item.SteelShovelItem;
import net.mcreator.stmwr.item.SteelPickaxeItem;
import net.mcreator.stmwr.item.SteelIngotItem;
import net.mcreator.stmwr.item.SteelHoeItem;
import net.mcreator.stmwr.item.SteelCoreItem;
import net.mcreator.stmwr.item.SteelAxeItem;
import net.mcreator.stmwr.item.SteelArmorItem;
import net.mcreator.stmwr.item.SpellBookOfTransmutationItem;
import net.mcreator.stmwr.item.SpellBookOfLightningItem;
import net.mcreator.stmwr.item.SpellBookOfHealingItem;
import net.mcreator.stmwr.item.SpellBookApplicatorTutorialSheetItem;
import net.mcreator.stmwr.item.SpeedTotemT3Item;
import net.mcreator.stmwr.item.SpeedTotemT2Item;
import net.mcreator.stmwr.item.SpeedTotemT1Item;
import net.mcreator.stmwr.item.ShreddedBeefItem;
import net.mcreator.stmwr.item.SausageItem;
import net.mcreator.stmwr.item.SandWormScaleItem;
import net.mcreator.stmwr.item.SandWormCallerItem;
import net.mcreator.stmwr.item.RawTotemItem;
import net.mcreator.stmwr.item.RawSausageItem;
import net.mcreator.stmwr.item.PortableOvenItem;
import net.mcreator.stmwr.item.PortableCrucibleItem;
import net.mcreator.stmwr.item.PlastikaItem;
import net.mcreator.stmwr.item.PizzaSliceItem;
import net.mcreator.stmwr.item.PizzaItem;
import net.mcreator.stmwr.item.PistolItem;
import net.mcreator.stmwr.item.PistolAmmoItem;
import net.mcreator.stmwr.item.PikastaffItem;
import net.mcreator.stmwr.item.PepperoniItem;
import net.mcreator.stmwr.item.NoobishTrialCoinItem;
import net.mcreator.stmwr.item.NightvisionTotemItem;
import net.mcreator.stmwr.item.MysticalPageItem;
import net.mcreator.stmwr.item.MysteriousScrapItem;
import net.mcreator.stmwr.item.MutantWhistleItem;
import net.mcreator.stmwr.item.MutantGoopItem;
import net.mcreator.stmwr.item.MinerAppleItem;
import net.mcreator.stmwr.item.MilitariaItem;
import net.mcreator.stmwr.item.MasterCubbyPackItem;
import net.mcreator.stmwr.item.MagiciteDustItem;
import net.mcreator.stmwr.item.MagicianAppleItem;
import net.mcreator.stmwr.item.MagicCarrotItem;
import net.mcreator.stmwr.item.LightningWandItem;
import net.mcreator.stmwr.item.LightningFragmentItem;
import net.mcreator.stmwr.item.LandOfTheSteveCowsItem;
import net.mcreator.stmwr.item.KnifeItem;
import net.mcreator.stmwr.item.KeyPieceItem;
import net.mcreator.stmwr.item.JumpboostTotemT3Item;
import net.mcreator.stmwr.item.JumpboostTotemT2Item;
import net.mcreator.stmwr.item.JumpboostTotemT1Item;
import net.mcreator.stmwr.item.IronSpikeItem;
import net.mcreator.stmwr.item.InfinititeScrapItem;
import net.mcreator.stmwr.item.InfinititeMoldItem;
import net.mcreator.stmwr.item.InfinititeIngotItem;
import net.mcreator.stmwr.item.InfinititeCoreItem;
import net.mcreator.stmwr.item.InfinititeArmorItem;
import net.mcreator.stmwr.item.InfiniBoingAppleItem;
import net.mcreator.stmwr.item.IceShardItem;
import net.mcreator.stmwr.item.HealthTotemT3Item;
import net.mcreator.stmwr.item.HealingWandItem;
import net.mcreator.stmwr.item.HealingTotemT2Item;
import net.mcreator.stmwr.item.HealingTotemItem;
import net.mcreator.stmwr.item.HealerAppleItem;
import net.mcreator.stmwr.item.HasteTotemT3Item;
import net.mcreator.stmwr.item.HasteTotemT2Item;
import net.mcreator.stmwr.item.HasteTotemT1Item;
import net.mcreator.stmwr.item.GoopItem;
import net.mcreator.stmwr.item.GodliumSwordItem;
import net.mcreator.stmwr.item.GodliumShovelItem;
import net.mcreator.stmwr.item.GodliumPickaxeItem;
import net.mcreator.stmwr.item.GodliumIngotItem;
import net.mcreator.stmwr.item.GodliumHoeItem;
import net.mcreator.stmwr.item.GodliumCoreItem;
import net.mcreator.stmwr.item.GodliumAxeItem;
import net.mcreator.stmwr.item.GodliumArmorItem;
import net.mcreator.stmwr.item.GiantSteveCowHeartItem;
import net.mcreator.stmwr.item.GiantCallerItem;
import net.mcreator.stmwr.item.GearCoreItem;
import net.mcreator.stmwr.item.FireproofTotemItem;
import net.mcreator.stmwr.item.EmptySpellBookItem;
import net.mcreator.stmwr.item.EasterEggItem;
import net.mcreator.stmwr.item.DurableAppleItem;
import net.mcreator.stmwr.item.DoughItem;
import net.mcreator.stmwr.item.DirtNuggetItem;
import net.mcreator.stmwr.item.CreationOrbItem;
import net.mcreator.stmwr.item.CrateTotemItem;
import net.mcreator.stmwr.item.ChocolateItem;
import net.mcreator.stmwr.item.CheeseStickItem;
import net.mcreator.stmwr.item.CheeseItem;
import net.mcreator.stmwr.item.CastingWandarItem;
import net.mcreator.stmwr.item.CannedPikachuItem;
import net.mcreator.stmwr.item.CanItem;
import net.mcreator.stmwr.item.BuildingWandarItem;
import net.mcreator.stmwr.item.BoosterAppleItem;
import net.mcreator.stmwr.item.BlazedSwordItem;
import net.mcreator.stmwr.item.BlazedShovelItem;
import net.mcreator.stmwr.item.BlazedPickaxeItem;
import net.mcreator.stmwr.item.BlazedIngotItem;
import net.mcreator.stmwr.item.BlazedHoeItem;
import net.mcreator.stmwr.item.BlazedCoreItem;
import net.mcreator.stmwr.item.BlazedAxeItem;
import net.mcreator.stmwr.item.BlazedArmorItem;
import net.mcreator.stmwr.item.BasicCubbyPackItem;
import net.mcreator.stmwr.item.AtomSmasherItem;
import net.mcreator.stmwr.item.AssaultRifleItem;
import net.mcreator.stmwr.item.AssaultRifleAmmoItem;
import net.mcreator.stmwr.item.AnimalStrapItem;
import net.mcreator.stmwr.item.AdvancedWandStickItem;
import net.mcreator.stmwr.item.AdvancedTotemBaseItem;
import net.mcreator.stmwr.item.AdvancedMaterialItem;
import net.mcreator.stmwr.item.AdvancedCubbyPackItem;
import net.mcreator.stmwr.StmwrMod;

public class StmwrModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, StmwrMod.MODID);
	public static final RegistryObject<Item> ATOM_SMASHER = REGISTRY.register("atom_smasher", () -> new AtomSmasherItem());
	public static final RegistryObject<Item> DIRT_NUGGET = REGISTRY.register("dirt_nugget", () -> new DirtNuggetItem());
	public static final RegistryObject<Item> MAGICITE_DUST = REGISTRY.register("magicite_dust", () -> new MagiciteDustItem());
	public static final RegistryObject<Item> MAGICITE_ORE = block(StmwrModBlocks.MAGICITE_ORE);
	public static final RegistryObject<Item> MAGICITE_BLOCK = block(StmwrModBlocks.MAGICITE_BLOCK);
	public static final RegistryObject<Item> PLASTIKA = REGISTRY.register("plastika", () -> new PlastikaItem());
	public static final RegistryObject<Item> PLASTICILIA = block(StmwrModBlocks.PLASTICILIA);
	public static final RegistryObject<Item> GODLIUM_INGOT = REGISTRY.register("godlium_ingot", () -> new GodliumIngotItem());
	public static final RegistryObject<Item> GODLIUM_ORE = block(StmwrModBlocks.GODLIUM_ORE);
	public static final RegistryObject<Item> GODLIUM_BLOCK = block(StmwrModBlocks.GODLIUM_BLOCK);
	public static final RegistryObject<Item> GODLIUM_PICKAXE = REGISTRY.register("godlium_pickaxe", () -> new GodliumPickaxeItem());
	public static final RegistryObject<Item> GODLIUM_AXE = REGISTRY.register("godlium_axe", () -> new GodliumAxeItem());
	public static final RegistryObject<Item> GODLIUM_SWORD = REGISTRY.register("godlium_sword", () -> new GodliumSwordItem());
	public static final RegistryObject<Item> GODLIUM_SHOVEL = REGISTRY.register("godlium_shovel", () -> new GodliumShovelItem());
	public static final RegistryObject<Item> GODLIUM_HOE = REGISTRY.register("godlium_hoe", () -> new GodliumHoeItem());
	public static final RegistryObject<Item> GODLIUM_ARMOR_HELMET = REGISTRY.register("godlium_armor_helmet", () -> new GodliumArmorItem.Helmet());
	public static final RegistryObject<Item> GODLIUM_ARMOR_CHESTPLATE = REGISTRY.register("godlium_armor_chestplate", () -> new GodliumArmorItem.Chestplate());
	public static final RegistryObject<Item> GODLIUM_ARMOR_LEGGINGS = REGISTRY.register("godlium_armor_leggings", () -> new GodliumArmorItem.Leggings());
	public static final RegistryObject<Item> GODLIUM_ARMOR_BOOTS = REGISTRY.register("godlium_armor_boots", () -> new GodliumArmorItem.Boots());
	public static final RegistryObject<Item> ULTRITE = REGISTRY.register("ultrite", () -> new UltriteItem());
	public static final RegistryObject<Item> RAW_TOTEM = REGISTRY.register("raw_totem", () -> new RawTotemItem());
	public static final RegistryObject<Item> WAND_STICK = REGISTRY.register("wand_stick", () -> new WandStickItem());
	public static final RegistryObject<Item> HEALING_TOTEM = REGISTRY.register("healing_totem", () -> new HealingTotemItem());
	public static final RegistryObject<Item> HEALING_TOTEM_T_2 = REGISTRY.register("healing_totem_t_2", () -> new HealingTotemT2Item());
	public static final RegistryObject<Item> HEALTH_TOTEM_T_3 = REGISTRY.register("health_totem_t_3", () -> new HealthTotemT3Item());
	public static final RegistryObject<Item> SPEED_TOTEM_T_1 = REGISTRY.register("speed_totem_t_1", () -> new SpeedTotemT1Item());
	public static final RegistryObject<Item> SPEED_TOTEM_T_2 = REGISTRY.register("speed_totem_t_2", () -> new SpeedTotemT2Item());
	public static final RegistryObject<Item> SPEED_TOTEM_T_3 = REGISTRY.register("speed_totem_t_3", () -> new SpeedTotemT3Item());
	public static final RegistryObject<Item> NIGHTVISION_TOTEM = REGISTRY.register("nightvision_totem", () -> new NightvisionTotemItem());
	public static final RegistryObject<Item> JUMPBOOST_TOTEM_T_1 = REGISTRY.register("jumpboost_totem_t_1", () -> new JumpboostTotemT1Item());
	public static final RegistryObject<Item> JUMPBOOST_TOTEM_T_2 = REGISTRY.register("jumpboost_totem_t_2", () -> new JumpboostTotemT2Item());
	public static final RegistryObject<Item> JUMPBOOST_TOTEM_T_3 = REGISTRY.register("jumpboost_totem_t_3", () -> new JumpboostTotemT3Item());
	public static final RegistryObject<Item> HASTE_TOTEM_T_1 = REGISTRY.register("haste_totem_t_1", () -> new HasteTotemT1Item());
	public static final RegistryObject<Item> HASTE_TOTEM_T_2 = REGISTRY.register("haste_totem_t_2", () -> new HasteTotemT2Item());
	public static final RegistryObject<Item> HASTE_TOTEM_T_3 = REGISTRY.register("haste_totem_t_3", () -> new HasteTotemT3Item());
	public static final RegistryObject<Item> ADVANCED_WAND_STICK = REGISTRY.register("advanced_wand_stick", () -> new AdvancedWandStickItem());
	public static final RegistryObject<Item> INFINITITE_INGOT = REGISTRY.register("infinitite_ingot", () -> new InfinititeIngotItem());
	public static final RegistryObject<Item> INFINITITE_ORE = block(StmwrModBlocks.INFINITITE_ORE);
	public static final RegistryObject<Item> INFINITITE_BLOCK = block(StmwrModBlocks.INFINITITE_BLOCK);
	public static final RegistryObject<Item> BLAZED_INGOT = REGISTRY.register("blazed_ingot", () -> new BlazedIngotItem());
	public static final RegistryObject<Item> BLAZED_ORE = block(StmwrModBlocks.BLAZED_ORE);
	public static final RegistryObject<Item> BLAZED_BLOCK = block(StmwrModBlocks.BLAZED_BLOCK);
	public static final RegistryObject<Item> BLAZED_PICKAXE = REGISTRY.register("blazed_pickaxe", () -> new BlazedPickaxeItem());
	public static final RegistryObject<Item> BLAZED_AXE = REGISTRY.register("blazed_axe", () -> new BlazedAxeItem());
	public static final RegistryObject<Item> BLAZED_SWORD = REGISTRY.register("blazed_sword", () -> new BlazedSwordItem());
	public static final RegistryObject<Item> BLAZED_SHOVEL = REGISTRY.register("blazed_shovel", () -> new BlazedShovelItem());
	public static final RegistryObject<Item> BLAZED_HOE = REGISTRY.register("blazed_hoe", () -> new BlazedHoeItem());
	public static final RegistryObject<Item> BLAZED_ARMOR_HELMET = REGISTRY.register("blazed_armor_helmet", () -> new BlazedArmorItem.Helmet());
	public static final RegistryObject<Item> BLAZED_ARMOR_CHESTPLATE = REGISTRY.register("blazed_armor_chestplate", () -> new BlazedArmorItem.Chestplate());
	public static final RegistryObject<Item> BLAZED_ARMOR_LEGGINGS = REGISTRY.register("blazed_armor_leggings", () -> new BlazedArmorItem.Leggings());
	public static final RegistryObject<Item> BLAZED_ARMOR_BOOTS = REGISTRY.register("blazed_armor_boots", () -> new BlazedArmorItem.Boots());
	public static final RegistryObject<Item> DOUGH = REGISTRY.register("dough", () -> new DoughItem());
	public static final RegistryObject<Item> ANIMAL_STRAP = REGISTRY.register("animal_strap", () -> new AnimalStrapItem());
	public static final RegistryObject<Item> STORUM = REGISTRY.register("storum", () -> new StorumItem());
	public static final RegistryObject<Item> STORUM_ORE = block(StmwrModBlocks.STORUM_ORE);
	public static final RegistryObject<Item> STORUM_BLOCK = block(StmwrModBlocks.STORUM_BLOCK);
	public static final RegistryObject<Item> FIREPROOF_TOTEM = REGISTRY.register("fireproof_totem", () -> new FireproofTotemItem());
	public static final RegistryObject<Item> KNIFE = REGISTRY.register("knife", () -> new KnifeItem());
	public static final RegistryObject<Item> RAW_SAUSAGE = REGISTRY.register("raw_sausage", () -> new RawSausageItem());
	public static final RegistryObject<Item> SAUSAGE = REGISTRY.register("sausage", () -> new SausageItem());
	public static final RegistryObject<Item> TRIAL_BRICK = block(StmwrModBlocks.TRIAL_BRICK);
	public static final RegistryObject<Item> STEVE_COW_HORN = REGISTRY.register("steve_cow_horn", () -> new SteveCowHornItem());
	public static final RegistryObject<Item> STEVE_COW_SPAWN_EGG = REGISTRY.register("steve_cow_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.STEVE_COW, -16711885, -16711732, new Item.Properties()));
	public static final RegistryObject<Item> LAND_OF_THE_STEVE_COWS = REGISTRY.register("land_of_the_steve_cows", () -> new LandOfTheSteveCowsItem());
	public static final RegistryObject<Item> KEY_PIECE = REGISTRY.register("key_piece", () -> new KeyPieceItem());
	public static final RegistryObject<Item> STEVUM = REGISTRY.register("stevum", () -> new StevumItem());
	public static final RegistryObject<Item> STEVUM_ORE = block(StmwrModBlocks.STEVUM_ORE);
	public static final RegistryObject<Item> STEVUM_BLOCK = block(StmwrModBlocks.STEVUM_BLOCK);
	public static final RegistryObject<Item> GIANT_STEVE_COW_SPAWN_EGG = REGISTRY.register("giant_steve_cow_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.GIANT_STEVE_COW, -16724788, -16711732, new Item.Properties()));
	public static final RegistryObject<Item> GIANT_STEVE_COW_HEART = REGISTRY.register("giant_steve_cow_heart", () -> new GiantSteveCowHeartItem());
	public static final RegistryObject<Item> GIANT_CALLER = REGISTRY.register("giant_caller", () -> new GiantCallerItem());
	public static final RegistryObject<Item> UGLUM = REGISTRY.register("uglum", () -> new UglumItem());
	public static final RegistryObject<Item> PIKACHU_SPAWN_EGG = REGISTRY.register("pikachu_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.PIKACHU, -256, -65536, new Item.Properties()));
	public static final RegistryObject<Item> PIKASTAFF = REGISTRY.register("pikastaff", () -> new PikastaffItem());
	public static final RegistryObject<Item> MYSTERIOUS_SCRAP = REGISTRY.register("mysterious_scrap", () -> new MysteriousScrapItem());
	public static final RegistryObject<Item> SURVIVOR_SPAWN_EGG = REGISTRY.register("survivor_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.SURVIVOR, -52225, -13261, new Item.Properties()));
	public static final RegistryObject<Item> ADVANCED_MATERIAL = REGISTRY.register("advanced_material", () -> new AdvancedMaterialItem());
	public static final RegistryObject<Item> SOLDIER_SPAWN_EGG = REGISTRY.register("soldier_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.SOLDIER, -16737997, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> MUTANT_GOOP = REGISTRY.register("mutant_goop", () -> new MutantGoopItem());
	public static final RegistryObject<Item> MUTANT_BOSS_SPAWN_EGG = REGISTRY.register("mutant_boss_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.MUTANT_BOSS, -16737946, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> MILITARIA = REGISTRY.register("militaria", () -> new MilitariaItem());
	public static final RegistryObject<Item> MUTANT_WHISTLE = REGISTRY.register("mutant_whistle", () -> new MutantWhistleItem());
	public static final RegistryObject<Item> GOOP = REGISTRY.register("goop", () -> new GoopItem());
	public static final RegistryObject<Item> MUTANT_WORM_SPAWN_EGG = REGISTRY.register("mutant_worm_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.MUTANT_WORM, -16777216, -1, new Item.Properties()));
	public static final RegistryObject<Item> STEEL_INGOT = REGISTRY.register("steel_ingot", () -> new SteelIngotItem());
	public static final RegistryObject<Item> STEEL_ORE = block(StmwrModBlocks.STEEL_ORE);
	public static final RegistryObject<Item> STEEL_BLOCK = block(StmwrModBlocks.STEEL_BLOCK);
	public static final RegistryObject<Item> STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", () -> new SteelPickaxeItem());
	public static final RegistryObject<Item> STEEL_AXE = REGISTRY.register("steel_axe", () -> new SteelAxeItem());
	public static final RegistryObject<Item> STEEL_SWORD = REGISTRY.register("steel_sword", () -> new SteelSwordItem());
	public static final RegistryObject<Item> STEEL_SHOVEL = REGISTRY.register("steel_shovel", () -> new SteelShovelItem());
	public static final RegistryObject<Item> STEEL_HOE = REGISTRY.register("steel_hoe", () -> new SteelHoeItem());
	public static final RegistryObject<Item> STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", () -> new SteelArmorItem.Helmet());
	public static final RegistryObject<Item> STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate", () -> new SteelArmorItem.Chestplate());
	public static final RegistryObject<Item> STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", () -> new SteelArmorItem.Leggings());
	public static final RegistryObject<Item> STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", () -> new SteelArmorItem.Boots());
	public static final RegistryObject<Item> CHEESE = REGISTRY.register("cheese", () -> new CheeseItem());
	public static final RegistryObject<Item> CHEESE_STICK = REGISTRY.register("cheese_stick", () -> new CheeseStickItem());
	public static final RegistryObject<Item> SHREDDED_BEEF = REGISTRY.register("shredded_beef", () -> new ShreddedBeefItem());
	public static final RegistryObject<Item> TORTILLA = REGISTRY.register("tortilla", () -> new TortillaItem());
	public static final RegistryObject<Item> TACO = REGISTRY.register("taco", () -> new TacoItem());
	public static final RegistryObject<Item> PORTABLE_OVEN = REGISTRY.register("portable_oven", () -> new PortableOvenItem());
	public static final RegistryObject<Item> MAGIC_CARROT = REGISTRY.register("magic_carrot", () -> new MagicCarrotItem());
	public static final RegistryObject<Item> PIZZA = REGISTRY.register("pizza", () -> new PizzaItem());
	public static final RegistryObject<Item> PIZZA_SLICE = REGISTRY.register("pizza_slice", () -> new PizzaSliceItem());
	public static final RegistryObject<Item> CREATION_ORB = REGISTRY.register("creation_orb", () -> new CreationOrbItem());
	public static final RegistryObject<Item> CHOCOLATE = REGISTRY.register("chocolate", () -> new ChocolateItem());
	public static final RegistryObject<Item> STRENGTH_TOTEM_T_1 = REGISTRY.register("strength_totem_t_1", () -> new StrengthTotemT1Item());
	public static final RegistryObject<Item> STRENGTH_TOTEM_T_2 = REGISTRY.register("strength_totem_t_2", () -> new StrengthTotemT2Item());
	public static final RegistryObject<Item> STRENGTH_TOTEM_T_3 = REGISTRY.register("strength_totem_t_3", () -> new StrengthTotemT3Item());
	public static final RegistryObject<Item> MODIFIER_TABLE = block(StmwrModBlocks.MODIFIER_TABLE);
	public static final RegistryObject<Item> ICE_SHARD = REGISTRY.register("ice_shard", () -> new IceShardItem());
	public static final RegistryObject<Item> FROST_ZOMBIE_SPAWN_EGG = REGISTRY.register("frost_zombie_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.FROST_ZOMBIE, -16711732, -16751002, new Item.Properties()));
	public static final RegistryObject<Item> PISTOL_AMMO = REGISTRY.register("pistol_ammo", () -> new PistolAmmoItem());
	public static final RegistryObject<Item> PISTOL = REGISTRY.register("pistol", () -> new PistolItem());
	public static final RegistryObject<Item> GAS_MASK_ZOMBIE_SPAWN_EGG = REGISTRY.register("gas_mask_zombie_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.GAS_MASK_ZOMBIE, -16751104, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> NOOBISH_TRIAL_COIN = REGISTRY.register("noobish_trial_coin", () -> new NoobishTrialCoinItem());
	public static final RegistryObject<Item> TOTEM_OF_THE_GOOP = REGISTRY.register("totem_of_the_goop", () -> new TotemOfTheGoopItem());
	public static final RegistryObject<Item> TOTEM_OF_THE_COW = REGISTRY.register("totem_of_the_cow", () -> new TotemOfTheCowItem());
	public static final RegistryObject<Item> ADVANCED_TOTEM_BASE = REGISTRY.register("advanced_totem_base", () -> new AdvancedTotemBaseItem());
	public static final RegistryObject<Item> PORTABLE_CRUCIBLE = REGISTRY.register("portable_crucible", () -> new PortableCrucibleItem());
	public static final RegistryObject<Item> TOTEM_OF_SLOW_FALLING = REGISTRY.register("totem_of_slow_falling", () -> new TotemOfSlowFallingItem());
	public static final RegistryObject<Item> BASIC_CUBBY_CUBE = block(StmwrModBlocks.BASIC_CUBBY_CUBE);
	public static final RegistryObject<Item> BASIC_CUBBY_PACK = REGISTRY.register("basic_cubby_pack", () -> new BasicCubbyPackItem());
	public static final RegistryObject<Item> STORALIUM = REGISTRY.register("storalium", () -> new StoraliumItem());
	public static final RegistryObject<Item> ADVANCED_CUBBY_CUBE = block(StmwrModBlocks.ADVANCED_CUBBY_CUBE);
	public static final RegistryObject<Item> ADVANCED_CUBBY_PACK = REGISTRY.register("advanced_cubby_pack", () -> new AdvancedCubbyPackItem());
	public static final RegistryObject<Item> MASTER_CUBBY_CUBE = block(StmwrModBlocks.MASTER_CUBBY_CUBE);
	public static final RegistryObject<Item> MASTER_CUBBY_PACK = REGISTRY.register("master_cubby_pack", () -> new MasterCubbyPackItem());
	public static final RegistryObject<Item> WANDAR_CORE = REGISTRY.register("wandar_core", () -> new WandarCoreItem());
	public static final RegistryObject<Item> CASTING_WANDAR = REGISTRY.register("casting_wandar", () -> new CastingWandarItem());
	public static final RegistryObject<Item> BUILDING_WANDAR = REGISTRY.register("building_wandar", () -> new BuildingWandarItem());
	public static final RegistryObject<Item> TRAPPED_WIZARD_SPAWN_EGG = REGISTRY.register("trapped_wizard_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.TRAPPED_WIZARD, -13421569, -16751002, new Item.Properties()));
	public static final RegistryObject<Item> WEAK_SOUL = REGISTRY.register("weak_soul", () -> new WeakSoulItem());
	public static final RegistryObject<Item> WIZARD_WORLD = REGISTRY.register("wizard_world", () -> new WizardWorldItem());
	public static final RegistryObject<Item> MYSTICAL_PAGE = REGISTRY.register("mystical_page", () -> new MysticalPageItem());
	public static final RegistryObject<Item> JUNIOR_WIZARD_SPAWN_EGG = REGISTRY.register("junior_wizard_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.JUNIOR_WIZARD, -3407668, -16737946, new Item.Properties()));
	public static final RegistryObject<Item> STRONG_SOUL = REGISTRY.register("strong_soul", () -> new StrongSoulItem());
	public static final RegistryObject<Item> DANGEROUS_WIZARD_SPAWN_EGG = REGISTRY.register("dangerous_wizard_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.DANGEROUS_WIZARD, -13434829, -3407668, new Item.Properties()));
	public static final RegistryObject<Item> EMPTY_SPELL_BOOK = REGISTRY.register("empty_spell_book", () -> new EmptySpellBookItem());
	public static final RegistryObject<Item> HEALING_WAND = REGISTRY.register("healing_wand", () -> new HealingWandItem());
	public static final RegistryObject<Item> SPELL_BOOK_OF_HEALING = REGISTRY.register("spell_book_of_healing", () -> new SpellBookOfHealingItem());
	public static final RegistryObject<Item> TOTEM_OF_LEVITATION = REGISTRY.register("totem_of_levitation", () -> new TotemOfLevitationItem());
	public static final RegistryObject<Item> TRANSMUTATED_GELATIN = block(StmwrModBlocks.TRANSMUTATED_GELATIN);
	public static final RegistryObject<Item> WAND_OF_TRANSMUTATION = REGISTRY.register("wand_of_transmutation", () -> new WandOfTransmutationItem());
	public static final RegistryObject<Item> WAND_OF_THE_TOWER = REGISTRY.register("wand_of_the_tower", () -> new WandOfTheTowerItem());
	public static final RegistryObject<Item> INFINITITE_SCRAP = REGISTRY.register("infinitite_scrap", () -> new InfinititeScrapItem());
	public static final RegistryObject<Item> INFINITITE_MOLD = REGISTRY.register("infinitite_mold", () -> new InfinititeMoldItem());
	public static final RegistryObject<Item> INFINITITE_ARMOR_HELMET = REGISTRY.register("infinitite_armor_helmet", () -> new InfinititeArmorItem.Helmet());
	public static final RegistryObject<Item> INFINITITE_ARMOR_CHESTPLATE = REGISTRY.register("infinitite_armor_chestplate", () -> new InfinititeArmorItem.Chestplate());
	public static final RegistryObject<Item> INFINITITE_ARMOR_LEGGINGS = REGISTRY.register("infinitite_armor_leggings", () -> new InfinititeArmorItem.Leggings());
	public static final RegistryObject<Item> INFINITITE_ARMOR_BOOTS = REGISTRY.register("infinitite_armor_boots", () -> new InfinititeArmorItem.Boots());
	public static final RegistryObject<Item> INFINITY_GOLEM_SPAWN_EGG = REGISTRY.register("infinity_golem_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.INFINITY_GOLEM, -10092442, -6711040, new Item.Properties()));
	public static final RegistryObject<Item> FINAL_BOSS_SPAWN_EGG = REGISTRY.register("final_boss_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.FINAL_BOSS, -13434829, -1, new Item.Properties()));
	public static final RegistryObject<Item> IRON_SPIKE = REGISTRY.register("iron_spike", () -> new IronSpikeItem());
	public static final RegistryObject<Item> PEPPERONI = REGISTRY.register("pepperoni", () -> new PepperoniItem());
	public static final RegistryObject<Item> TOTEMIC_CRATE = block(StmwrModBlocks.TOTEMIC_CRATE);
	public static final RegistryObject<Item> CRATE_TOTEM = REGISTRY.register("crate_totem", () -> new CrateTotemItem());
	public static final RegistryObject<Item> FOODY_CRATE = block(StmwrModBlocks.FOODY_CRATE);
	public static final RegistryObject<Item> MAGICIAN_CRATE = block(StmwrModBlocks.MAGICIAN_CRATE);
	public static final RegistryObject<Item> TRIAL_CRATE = block(StmwrModBlocks.TRIAL_CRATE);
	public static final RegistryObject<Item> STORING_CRATE = block(StmwrModBlocks.STORING_CRATE);
	public static final RegistryObject<Item> GENERAL_CRATE = block(StmwrModBlocks.GENERAL_CRATE);
	public static final RegistryObject<Item> VANILLA_CRATE = block(StmwrModBlocks.VANILLA_CRATE);
	public static final RegistryObject<Item> CAN = REGISTRY.register("can", () -> new CanItem());
	public static final RegistryObject<Item> CANNED_PIKACHU = REGISTRY.register("canned_pikachu", () -> new CannedPikachuItem());
	public static final RegistryObject<Item> UPGRADE_STATION = block(StmwrModBlocks.UPGRADE_STATION);
	public static final RegistryObject<Item> EASTER_EGG = REGISTRY.register("easter_egg", () -> new EasterEggItem());
	public static final RegistryObject<Item> UPGRADE_STATION_TUTORIAL_SHEET = REGISTRY.register("upgrade_station_tutorial_sheet", () -> new UpgradeStationTutorialSheetItem());
	public static final RegistryObject<Item> GODLIUM_CORE = REGISTRY.register("godlium_core", () -> new GodliumCoreItem());
	public static final RegistryObject<Item> GEAR_CORE = REGISTRY.register("gear_core", () -> new GearCoreItem());
	public static final RegistryObject<Item> GEAR_CRATE = block(StmwrModBlocks.GEAR_CRATE);
	public static final RegistryObject<Item> BLAZED_CORE = REGISTRY.register("blazed_core", () -> new BlazedCoreItem());
	public static final RegistryObject<Item> STEEL_CORE = REGISTRY.register("steel_core", () -> new SteelCoreItem());
	public static final RegistryObject<Item> INFINITITE_CORE = REGISTRY.register("infinitite_core", () -> new InfinititeCoreItem());
	public static final RegistryObject<Item> SPELL_BOOK_APPLICATOR = block(StmwrModBlocks.SPELL_BOOK_APPLICATOR);
	public static final RegistryObject<Item> SPELL_BOOK_APPLICATOR_TUTORIAL_SHEET = REGISTRY.register("spell_book_applicator_tutorial_sheet", () -> new SpellBookApplicatorTutorialSheetItem());
	public static final RegistryObject<Item> SPELL_BOOK_OF_TRANSMUTATION = REGISTRY.register("spell_book_of_transmutation", () -> new SpellBookOfTransmutationItem());
	public static final RegistryObject<Item> MAGICIAN_APPLE = REGISTRY.register("magician_apple", () -> new MagicianAppleItem());
	public static final RegistryObject<Item> APPLE_CRATE = block(StmwrModBlocks.APPLE_CRATE);
	public static final RegistryObject<Item> BOOSTER_APPLE = REGISTRY.register("booster_apple", () -> new BoosterAppleItem());
	public static final RegistryObject<Item> INFINI_BOING_APPLE = REGISTRY.register("infini_boing_apple", () -> new InfiniBoingAppleItem());
	public static final RegistryObject<Item> DURABLE_APPLE = REGISTRY.register("durable_apple", () -> new DurableAppleItem());
	public static final RegistryObject<Item> MINER_APPLE = REGISTRY.register("miner_apple", () -> new MinerAppleItem());
	public static final RegistryObject<Item> HEALER_APPLE = REGISTRY.register("healer_apple", () -> new HealerAppleItem());
	public static final RegistryObject<Item> WINGED_APPLE = REGISTRY.register("winged_apple", () -> new WingedAppleItem());
	public static final RegistryObject<Item> MILITARIA_TRADING_OUTPOST = block(StmwrModBlocks.MILITARIA_TRADING_OUTPOST);
	public static final RegistryObject<Item> MAGIC_VILLAGER_TRADING_STATION = block(StmwrModBlocks.MAGIC_VILLAGER_TRADING_STATION);
	public static final RegistryObject<Item> LIGHTNING_FLINGER_SPAWN_EGG = REGISTRY.register("lightning_flinger_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.LIGHTNING_FLINGER, -6711040, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> LIGHTNING_FRAGMENT = REGISTRY.register("lightning_fragment", () -> new LightningFragmentItem());
	public static final RegistryObject<Item> SPELL_BOOK_OF_LIGHTNING = REGISTRY.register("spell_book_of_lightning", () -> new SpellBookOfLightningItem());
	public static final RegistryObject<Item> LIGHTNING_WAND = REGISTRY.register("lightning_wand", () -> new LightningWandItem());
	public static final RegistryObject<Item> SAND_WORM_SCALE = REGISTRY.register("sand_worm_scale", () -> new SandWormScaleItem());
	public static final RegistryObject<Item> SAND_WORM_SPAWN_EGG = REGISTRY.register("sand_worm_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.SAND_WORM, -13261, -13210, new Item.Properties()));
	public static final RegistryObject<Item> MINOR_SAND_WORM_SPAWN_EGG = REGISTRY.register("minor_sand_worm_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.MINOR_SAND_WORM, -26266, -3394816, new Item.Properties()));
	public static final RegistryObject<Item> SAND_WORM_CALLER = REGISTRY.register("sand_worm_caller", () -> new SandWormCallerItem());
	public static final RegistryObject<Item> ASSAULT_RIFLE = REGISTRY.register("assault_rifle", () -> new AssaultRifleItem());
	public static final RegistryObject<Item> ASSAULT_RIFLE_AMMO = REGISTRY.register("assault_rifle_ammo", () -> new AssaultRifleAmmoItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
