
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.stmwr.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.stmwr.item.WandarItem;
import net.mcreator.stmwr.item.WandStickItem;
import net.mcreator.stmwr.item.UltriteItem;
import net.mcreator.stmwr.item.UglumItem;
import net.mcreator.stmwr.item.TortillaItem;
import net.mcreator.stmwr.item.TacoItem;
import net.mcreator.stmwr.item.SuggestiumItem;
import net.mcreator.stmwr.item.StrengthTotemT3Item;
import net.mcreator.stmwr.item.StrengthTotemT2Item;
import net.mcreator.stmwr.item.StrengthTotemT1Item;
import net.mcreator.stmwr.item.StorumItem;
import net.mcreator.stmwr.item.StevumItem;
import net.mcreator.stmwr.item.SteveCowHornItem;
import net.mcreator.stmwr.item.SteelSwordItem;
import net.mcreator.stmwr.item.SteelShovelItem;
import net.mcreator.stmwr.item.SteelPickaxeItem;
import net.mcreator.stmwr.item.SteelIngotItem;
import net.mcreator.stmwr.item.SteelHoeItem;
import net.mcreator.stmwr.item.SteelAxeItem;
import net.mcreator.stmwr.item.SteelArmorItem;
import net.mcreator.stmwr.item.SpeedTotemT3Item;
import net.mcreator.stmwr.item.SpeedTotemT2Item;
import net.mcreator.stmwr.item.SpeedTotemT1Item;
import net.mcreator.stmwr.item.ShreddedBeefItem;
import net.mcreator.stmwr.item.SausageItem;
import net.mcreator.stmwr.item.RawTotemItem;
import net.mcreator.stmwr.item.RawSausageItem;
import net.mcreator.stmwr.item.PortableOvenItem;
import net.mcreator.stmwr.item.PlastikaItem;
import net.mcreator.stmwr.item.PizzaSliceItem;
import net.mcreator.stmwr.item.PizzaItem;
import net.mcreator.stmwr.item.PistolItem;
import net.mcreator.stmwr.item.PistolAmmoItem;
import net.mcreator.stmwr.item.PikastaffItem;
import net.mcreator.stmwr.item.NoobishTrialCoinItem;
import net.mcreator.stmwr.item.NightvisionTotemItem;
import net.mcreator.stmwr.item.MysteriousScrapItem;
import net.mcreator.stmwr.item.MutantWhistleItem;
import net.mcreator.stmwr.item.MutantGoopItem;
import net.mcreator.stmwr.item.MilitariaItem;
import net.mcreator.stmwr.item.MagiciteDustItem;
import net.mcreator.stmwr.item.MagicCarrotItem;
import net.mcreator.stmwr.item.LandOfTheSteveCowsItem;
import net.mcreator.stmwr.item.KnifeItem;
import net.mcreator.stmwr.item.KeyPieceItem;
import net.mcreator.stmwr.item.JumpboostTotemT3Item;
import net.mcreator.stmwr.item.JumpboostTotemT2Item;
import net.mcreator.stmwr.item.JumpboostTotemT1Item;
import net.mcreator.stmwr.item.IronWandItem;
import net.mcreator.stmwr.item.InfinititeIngotItem;
import net.mcreator.stmwr.item.IdkSomethingItem;
import net.mcreator.stmwr.item.IceShardItem;
import net.mcreator.stmwr.item.HealthTotemT3Item;
import net.mcreator.stmwr.item.HealingTotemT2Item;
import net.mcreator.stmwr.item.HealingTotemItem;
import net.mcreator.stmwr.item.HasteTotemT3Item;
import net.mcreator.stmwr.item.HasteTotemT2Item;
import net.mcreator.stmwr.item.HasteTotemT1Item;
import net.mcreator.stmwr.item.GoopItem;
import net.mcreator.stmwr.item.GodliumSwordItem;
import net.mcreator.stmwr.item.GodliumShovelItem;
import net.mcreator.stmwr.item.GodliumPickaxeItem;
import net.mcreator.stmwr.item.GodliumIngotItem;
import net.mcreator.stmwr.item.GodliumHoeItem;
import net.mcreator.stmwr.item.GodliumAxeItem;
import net.mcreator.stmwr.item.GodliumArmorItem;
import net.mcreator.stmwr.item.GiantSteveCowHeartItem;
import net.mcreator.stmwr.item.GiantCallerItem;
import net.mcreator.stmwr.item.FireproofTotemItem;
import net.mcreator.stmwr.item.DoughItem;
import net.mcreator.stmwr.item.DirtNuggetItem;
import net.mcreator.stmwr.item.CreationOrbItem;
import net.mcreator.stmwr.item.CoalWandItem;
import net.mcreator.stmwr.item.ChocolateItem;
import net.mcreator.stmwr.item.CheeseStickItem;
import net.mcreator.stmwr.item.CheeseItem;
import net.mcreator.stmwr.item.BuildersWandItem;
import net.mcreator.stmwr.item.BlazedSwordItem;
import net.mcreator.stmwr.item.BlazedShovelItem;
import net.mcreator.stmwr.item.BlazedPickaxeItem;
import net.mcreator.stmwr.item.BlazedIngotItem;
import net.mcreator.stmwr.item.BlazedHoeItem;
import net.mcreator.stmwr.item.BlazedAxeItem;
import net.mcreator.stmwr.item.BlazedArmorItem;
import net.mcreator.stmwr.item.AtomSmasherItem;
import net.mcreator.stmwr.item.AnimalStrapItem;
import net.mcreator.stmwr.item.AdvancedWandStickItem;
import net.mcreator.stmwr.item.AdvancedMaterialItem;
import net.mcreator.stmwr.StmwrMod;

public class StmwrModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, StmwrMod.MODID);
	public static final RegistryObject<Item> ATOM_SMASHER = REGISTRY.register("atom_smasher", () -> new AtomSmasherItem());
	public static final RegistryObject<Item> DIRT_NUGGET = REGISTRY.register("dirt_nugget", () -> new DirtNuggetItem());
	public static final RegistryObject<Item> MAGICITE_DUST = REGISTRY.register("magicite_dust", () -> new MagiciteDustItem());
	public static final RegistryObject<Item> MAGICITE_ORE = block(StmwrModBlocks.MAGICITE_ORE);
	public static final RegistryObject<Item> MAGICITE_BLOCK = block(StmwrModBlocks.MAGICITE_BLOCK);
	public static final RegistryObject<Item> PLASTIKA = REGISTRY.register("plastika", () -> new PlastikaItem());
	public static final RegistryObject<Item> PLASTICILIA = block(StmwrModBlocks.PLASTICILIA);
	public static final RegistryObject<Item> GODLIUM_INGOT = REGISTRY.register("godlium_ingot", () -> new GodliumIngotItem());
	public static final RegistryObject<Item> GODLIUM_ORE = block(StmwrModBlocks.GODLIUM_ORE);
	public static final RegistryObject<Item> GODLIUM_BLOCK = block(StmwrModBlocks.GODLIUM_BLOCK);
	public static final RegistryObject<Item> GODLIUM_PICKAXE = REGISTRY.register("godlium_pickaxe", () -> new GodliumPickaxeItem());
	public static final RegistryObject<Item> GODLIUM_AXE = REGISTRY.register("godlium_axe", () -> new GodliumAxeItem());
	public static final RegistryObject<Item> GODLIUM_SWORD = REGISTRY.register("godlium_sword", () -> new GodliumSwordItem());
	public static final RegistryObject<Item> GODLIUM_SHOVEL = REGISTRY.register("godlium_shovel", () -> new GodliumShovelItem());
	public static final RegistryObject<Item> GODLIUM_HOE = REGISTRY.register("godlium_hoe", () -> new GodliumHoeItem());
	public static final RegistryObject<Item> GODLIUM_ARMOR_HELMET = REGISTRY.register("godlium_armor_helmet", () -> new GodliumArmorItem.Helmet());
	public static final RegistryObject<Item> GODLIUM_ARMOR_CHESTPLATE = REGISTRY.register("godlium_armor_chestplate", () -> new GodliumArmorItem.Chestplate());
	public static final RegistryObject<Item> GODLIUM_ARMOR_LEGGINGS = REGISTRY.register("godlium_armor_leggings", () -> new GodliumArmorItem.Leggings());
	public static final RegistryObject<Item> GODLIUM_ARMOR_BOOTS = REGISTRY.register("godlium_armor_boots", () -> new GodliumArmorItem.Boots());
	public static final RegistryObject<Item> ULTRITE = REGISTRY.register("ultrite", () -> new UltriteItem());
	public static final RegistryObject<Item> RAW_TOTEM = REGISTRY.register("raw_totem", () -> new RawTotemItem());
	public static final RegistryObject<Item> WAND_STICK = REGISTRY.register("wand_stick", () -> new WandStickItem());
	public static final RegistryObject<Item> HEALING_TOTEM = REGISTRY.register("healing_totem", () -> new HealingTotemItem());
	public static final RegistryObject<Item> BUILDERS_WAND = REGISTRY.register("builders_wand", () -> new BuildersWandItem());
	public static final RegistryObject<Item> HEALING_TOTEM_T_2 = REGISTRY.register("healing_totem_t_2", () -> new HealingTotemT2Item());
	public static final RegistryObject<Item> HEALTH_TOTEM_T_3 = REGISTRY.register("health_totem_t_3", () -> new HealthTotemT3Item());
	public static final RegistryObject<Item> SPEED_TOTEM_T_1 = REGISTRY.register("speed_totem_t_1", () -> new SpeedTotemT1Item());
	public static final RegistryObject<Item> SPEED_TOTEM_T_2 = REGISTRY.register("speed_totem_t_2", () -> new SpeedTotemT2Item());
	public static final RegistryObject<Item> SPEED_TOTEM_T_3 = REGISTRY.register("speed_totem_t_3", () -> new SpeedTotemT3Item());
	public static final RegistryObject<Item> NIGHTVISION_TOTEM = REGISTRY.register("nightvision_totem", () -> new NightvisionTotemItem());
	public static final RegistryObject<Item> JUMPBOOST_TOTEM_T_1 = REGISTRY.register("jumpboost_totem_t_1", () -> new JumpboostTotemT1Item());
	public static final RegistryObject<Item> JUMPBOOST_TOTEM_T_2 = REGISTRY.register("jumpboost_totem_t_2", () -> new JumpboostTotemT2Item());
	public static final RegistryObject<Item> JUMPBOOST_TOTEM_T_3 = REGISTRY.register("jumpboost_totem_t_3", () -> new JumpboostTotemT3Item());
	public static final RegistryObject<Item> HASTE_TOTEM_T_1 = REGISTRY.register("haste_totem_t_1", () -> new HasteTotemT1Item());
	public static final RegistryObject<Item> HASTE_TOTEM_T_2 = REGISTRY.register("haste_totem_t_2", () -> new HasteTotemT2Item());
	public static final RegistryObject<Item> HASTE_TOTEM_T_3 = REGISTRY.register("haste_totem_t_3", () -> new HasteTotemT3Item());
	public static final RegistryObject<Item> WANDAR = REGISTRY.register("wandar", () -> new WandarItem());
	public static final RegistryObject<Item> ADVANCED_WAND_STICK = REGISTRY.register("advanced_wand_stick", () -> new AdvancedWandStickItem());
	public static final RegistryObject<Item> IRON_WAND = REGISTRY.register("iron_wand", () -> new IronWandItem());
	public static final RegistryObject<Item> COAL_WAND = REGISTRY.register("coal_wand", () -> new CoalWandItem());
	public static final RegistryObject<Item> INFINITITE_INGOT = REGISTRY.register("infinitite_ingot", () -> new InfinititeIngotItem());
	public static final RegistryObject<Item> INFINITITE_ORE = block(StmwrModBlocks.INFINITITE_ORE);
	public static final RegistryObject<Item> INFINITITE_BLOCK = block(StmwrModBlocks.INFINITITE_BLOCK);
	public static final RegistryObject<Item> BLAZED_INGOT = REGISTRY.register("blazed_ingot", () -> new BlazedIngotItem());
	public static final RegistryObject<Item> BLAZED_ORE = block(StmwrModBlocks.BLAZED_ORE);
	public static final RegistryObject<Item> BLAZED_BLOCK = block(StmwrModBlocks.BLAZED_BLOCK);
	public static final RegistryObject<Item> BLAZED_PICKAXE = REGISTRY.register("blazed_pickaxe", () -> new BlazedPickaxeItem());
	public static final RegistryObject<Item> BLAZED_AXE = REGISTRY.register("blazed_axe", () -> new BlazedAxeItem());
	public static final RegistryObject<Item> BLAZED_SWORD = REGISTRY.register("blazed_sword", () -> new BlazedSwordItem());
	public static final RegistryObject<Item> BLAZED_SHOVEL = REGISTRY.register("blazed_shovel", () -> new BlazedShovelItem());
	public static final RegistryObject<Item> BLAZED_HOE = REGISTRY.register("blazed_hoe", () -> new BlazedHoeItem());
	public static final RegistryObject<Item> BLAZED_ARMOR_HELMET = REGISTRY.register("blazed_armor_helmet", () -> new BlazedArmorItem.Helmet());
	public static final RegistryObject<Item> BLAZED_ARMOR_CHESTPLATE = REGISTRY.register("blazed_armor_chestplate", () -> new BlazedArmorItem.Chestplate());
	public static final RegistryObject<Item> BLAZED_ARMOR_LEGGINGS = REGISTRY.register("blazed_armor_leggings", () -> new BlazedArmorItem.Leggings());
	public static final RegistryObject<Item> BLAZED_ARMOR_BOOTS = REGISTRY.register("blazed_armor_boots", () -> new BlazedArmorItem.Boots());
	public static final RegistryObject<Item> DOUGH = REGISTRY.register("dough", () -> new DoughItem());
	public static final RegistryObject<Item> ANIMAL_STRAP = REGISTRY.register("animal_strap", () -> new AnimalStrapItem());
	public static final RegistryObject<Item> STORUM = REGISTRY.register("storum", () -> new StorumItem());
	public static final RegistryObject<Item> STORUM_ORE = block(StmwrModBlocks.STORUM_ORE);
	public static final RegistryObject<Item> STORUM_BLOCK = block(StmwrModBlocks.STORUM_BLOCK);
	public static final RegistryObject<Item> CUBBY_CUBE = block(StmwrModBlocks.CUBBY_CUBE);
	public static final RegistryObject<Item> FIREPROOF_TOTEM = REGISTRY.register("fireproof_totem", () -> new FireproofTotemItem());
	public static final RegistryObject<Item> KNIFE = REGISTRY.register("knife", () -> new KnifeItem());
	public static final RegistryObject<Item> RAW_SAUSAGE = REGISTRY.register("raw_sausage", () -> new RawSausageItem());
	public static final RegistryObject<Item> SAUSAGE = REGISTRY.register("sausage", () -> new SausageItem());
	public static final RegistryObject<Item> TRIAL_BRICK = block(StmwrModBlocks.TRIAL_BRICK);
	public static final RegistryObject<Item> STEVE_COW_HORN = REGISTRY.register("steve_cow_horn", () -> new SteveCowHornItem());
	public static final RegistryObject<Item> STEVE_COW_SPAWN_EGG = REGISTRY.register("steve_cow_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.STEVE_COW, -16711885, -16711732, new Item.Properties()));
	public static final RegistryObject<Item> LAND_OF_THE_STEVE_COWS = REGISTRY.register("land_of_the_steve_cows", () -> new LandOfTheSteveCowsItem());
	public static final RegistryObject<Item> KEY_PIECE = REGISTRY.register("key_piece", () -> new KeyPieceItem());
	public static final RegistryObject<Item> STEVUM = REGISTRY.register("stevum", () -> new StevumItem());
	public static final RegistryObject<Item> STEVUM_ORE = block(StmwrModBlocks.STEVUM_ORE);
	public static final RegistryObject<Item> STEVUM_BLOCK = block(StmwrModBlocks.STEVUM_BLOCK);
	public static final RegistryObject<Item> GIANT_STEVE_COW_SPAWN_EGG = REGISTRY.register("giant_steve_cow_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.GIANT_STEVE_COW, -16724788, -16711732, new Item.Properties()));
	public static final RegistryObject<Item> GIANT_STEVE_COW_HEART = REGISTRY.register("giant_steve_cow_heart", () -> new GiantSteveCowHeartItem());
	public static final RegistryObject<Item> GIANT_CALLER = REGISTRY.register("giant_caller", () -> new GiantCallerItem());
	public static final RegistryObject<Item> UGLUM = REGISTRY.register("uglum", () -> new UglumItem());
	public static final RegistryObject<Item> PIKACHU_SPAWN_EGG = REGISTRY.register("pikachu_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.PIKACHU, -256, -65536, new Item.Properties()));
	public static final RegistryObject<Item> PIKASTAFF = REGISTRY.register("pikastaff", () -> new PikastaffItem());
	public static final RegistryObject<Item> MYSTERIOUS_SCRAP = REGISTRY.register("mysterious_scrap", () -> new MysteriousScrapItem());
	public static final RegistryObject<Item> SURVIVOR_SPAWN_EGG = REGISTRY.register("survivor_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.SURVIVOR, -52225, -13261, new Item.Properties()));
	public static final RegistryObject<Item> ADVANCED_MATERIAL = REGISTRY.register("advanced_material", () -> new AdvancedMaterialItem());
	public static final RegistryObject<Item> SOLDIER_SPAWN_EGG = REGISTRY.register("soldier_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.SOLDIER, -16737997, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> MUTANT_GOOP = REGISTRY.register("mutant_goop", () -> new MutantGoopItem());
	public static final RegistryObject<Item> MUTANT_BOSS_SPAWN_EGG = REGISTRY.register("mutant_boss_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.MUTANT_BOSS, -16737946, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> MILITARIA = REGISTRY.register("militaria", () -> new MilitariaItem());
	public static final RegistryObject<Item> MUTANT_WHISTLE = REGISTRY.register("mutant_whistle", () -> new MutantWhistleItem());
	public static final RegistryObject<Item> GOOP = REGISTRY.register("goop", () -> new GoopItem());
	public static final RegistryObject<Item> MUTANT_WORM_SPAWN_EGG = REGISTRY.register("mutant_worm_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.MUTANT_WORM, -16777216, -1, new Item.Properties()));
	public static final RegistryObject<Item> STEEL_INGOT = REGISTRY.register("steel_ingot", () -> new SteelIngotItem());
	public static final RegistryObject<Item> STEEL_ORE = block(StmwrModBlocks.STEEL_ORE);
	public static final RegistryObject<Item> STEEL_BLOCK = block(StmwrModBlocks.STEEL_BLOCK);
	public static final RegistryObject<Item> STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", () -> new SteelPickaxeItem());
	public static final RegistryObject<Item> STEEL_AXE = REGISTRY.register("steel_axe", () -> new SteelAxeItem());
	public static final RegistryObject<Item> STEEL_SWORD = REGISTRY.register("steel_sword", () -> new SteelSwordItem());
	public static final RegistryObject<Item> STEEL_SHOVEL = REGISTRY.register("steel_shovel", () -> new SteelShovelItem());
	public static final RegistryObject<Item> STEEL_HOE = REGISTRY.register("steel_hoe", () -> new SteelHoeItem());
	public static final RegistryObject<Item> STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", () -> new SteelArmorItem.Helmet());
	public static final RegistryObject<Item> STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate", () -> new SteelArmorItem.Chestplate());
	public static final RegistryObject<Item> STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", () -> new SteelArmorItem.Leggings());
	public static final RegistryObject<Item> STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", () -> new SteelArmorItem.Boots());
	public static final RegistryObject<Item> SUGGESTIUM = REGISTRY.register("suggestium", () -> new SuggestiumItem());
	public static final RegistryObject<Item> SUGGESTIUM_ORE = block(StmwrModBlocks.SUGGESTIUM_ORE);
	public static final RegistryObject<Item> SUGGESTIUM_BLOCK = block(StmwrModBlocks.SUGGESTIUM_BLOCK);
	public static final RegistryObject<Item> IDK_SOMETHING = REGISTRY.register("idk_something", () -> new IdkSomethingItem());
	public static final RegistryObject<Item> CHEESE = REGISTRY.register("cheese", () -> new CheeseItem());
	public static final RegistryObject<Item> CHEESE_STICK = REGISTRY.register("cheese_stick", () -> new CheeseStickItem());
	public static final RegistryObject<Item> SHREDDED_BEEF = REGISTRY.register("shredded_beef", () -> new ShreddedBeefItem());
	public static final RegistryObject<Item> TORTILLA = REGISTRY.register("tortilla", () -> new TortillaItem());
	public static final RegistryObject<Item> TACO = REGISTRY.register("taco", () -> new TacoItem());
	public static final RegistryObject<Item> PORTABLE_OVEN = REGISTRY.register("portable_oven", () -> new PortableOvenItem());
	public static final RegistryObject<Item> MAGIC_CARROT = REGISTRY.register("magic_carrot", () -> new MagicCarrotItem());
	public static final RegistryObject<Item> PIZZA = REGISTRY.register("pizza", () -> new PizzaItem());
	public static final RegistryObject<Item> PIZZA_SLICE = REGISTRY.register("pizza_slice", () -> new PizzaSliceItem());
	public static final RegistryObject<Item> CREATION_ORB = REGISTRY.register("creation_orb", () -> new CreationOrbItem());
	public static final RegistryObject<Item> CHOCOLATE = REGISTRY.register("chocolate", () -> new ChocolateItem());
	public static final RegistryObject<Item> STRENGTH_TOTEM_T_1 = REGISTRY.register("strength_totem_t_1", () -> new StrengthTotemT1Item());
	public static final RegistryObject<Item> STRENGTH_TOTEM_T_2 = REGISTRY.register("strength_totem_t_2", () -> new StrengthTotemT2Item());
	public static final RegistryObject<Item> STRENGTH_TOTEM_T_3 = REGISTRY.register("strength_totem_t_3", () -> new StrengthTotemT3Item());
	public static final RegistryObject<Item> MODIFIER_TABLE = block(StmwrModBlocks.MODIFIER_TABLE);
	public static final RegistryObject<Item> ICE_SHARD = REGISTRY.register("ice_shard", () -> new IceShardItem());
	public static final RegistryObject<Item> FROST_ZOMBIE_SPAWN_EGG = REGISTRY.register("frost_zombie_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.FROST_ZOMBIE, -16711732, -16751002, new Item.Properties()));
	public static final RegistryObject<Item> PISTOL_AMMO = REGISTRY.register("pistol_ammo", () -> new PistolAmmoItem());
	public static final RegistryObject<Item> PISTOL = REGISTRY.register("pistol", () -> new PistolItem());
	public static final RegistryObject<Item> GAS_MASK_ZOMBIE_SPAWN_EGG = REGISTRY.register("gas_mask_zombie_spawn_egg", () -> new ForgeSpawnEggItem(StmwrModEntities.GAS_MASK_ZOMBIE, -16751104, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> NOOBISH_TRIAL_COIN = REGISTRY.register("noobish_trial_coin", () -> new NoobishTrialCoinItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
